"""
Narrative measures, computed from the transcript text alone.

These are re-implementations of the CLAN ``eval`` measures that ship with
AphasiaBank (MacWhinney et al.). CLAN itself needs a full CHAT-formatted
transcript; these versions need only the plain text, so they can be computed
for any narrative — including text generated by a language model.

Only word-level bookkeeping is needed: how many utterances, how many words,
how many distinct words. No part-of-speech tagger or other NLP model is
involved, which keeps this module dependency-free and fast.

NOTE: [design thought] the original project also estimated morpheme-based
measures (MLU_Morphemes) with a POS tagger. The final classifier does not use
them, so they are left out here to avoid a heavyweight spaCy dependency. If
you want them, the gold CLAN values are available as ``gold_MLU_Morphemes`` in
features.csv for the AphasiaBank transcripts.
"""

import re

# NOTE: [pedagogical] CLAN counts a "word" only over tokens that look like
# normal English words — punctuation and isolated digits are dropped. We
# approximate that with: starts with a letter, then letters/apostrophes/hyphens.
WORD_RE = re.compile(r"[A-Za-z][A-Za-z'\-]*")

# Utterance terminators. Transcripts put each utterance on its own sentence
# ended by ".", "!" or "?".
TERMINATOR_RE = re.compile(r"[.!?]+")

# NOTE: [design thought] CLAN's mean-length-of-utterance denominator excludes
# one-word acknowledgements ("yeah.", "no.") because they say nothing about
# syntactic planning. We approximate that by dropping any utterance that is a
# single one of these filler words.
MLU_FILLERS = {"yeah", "yes", "no", "ok", "okay", "hm", "hmm", "uh", "um",
               "uhuh", "hmhm", "mm", "mhm"}


def split_utterances(text):
    """Split a transcript into utterances at sentence-final punctuation."""
    utterances = []
    for chunk in re.split(r"(?<=[.!?])\s+", text.strip()):
        cleaned = TERMINATOR_RE.sub("", chunk).strip()
        if cleaned:
            utterances.append(cleaned)
    return utterances


def tokenize_words(utterance):
    """The word-like tokens of one utterance, lowercased."""
    return [match.group(0).lower() for match in WORD_RE.finditer(utterance)]


def compute(text):
    """All narrative measures for one transcript, as a dictionary.

    The five measures the classifier uses are Total_Utts, MLU_Utts,
    FREQ_types, FREQ_tokens and FREQ_TTR. MLU_Words is included as an extra
    you can switch on in config.FEATURES.
    """
    utterances = split_utterances(text)
    utterance_tokens = [tokenize_words(u) for u in utterances]
    all_tokens = [word for tokens in utterance_tokens for word in tokens]

    n_tokens = len(all_tokens)
    n_types = len(set(all_tokens))

    # Utterances that count toward mean length of utterance (see MLU_FILLERS).
    mlu_utterances = [tokens for tokens in utterance_tokens
                      if not (len(tokens) == 1 and tokens[0] in MLU_FILLERS)]

    return {
        "Total_Utts": len(utterances),
        "MLU_Utts": len(mlu_utterances),
        "MLU_Words": (sum(len(t) for t in mlu_utterances) / len(mlu_utterances)
                      if mlu_utterances else 0.0),
        "FREQ_types": n_types,
        "FREQ_tokens": n_tokens,
        "FREQ_TTR": n_types / n_tokens if n_tokens else 0.0,
    }


# The columns this module produces, in the order build_features.py writes them.
COLUMNS = ["Total_Utts", "MLU_Utts", "MLU_Words", "FREQ_types", "FREQ_tokens", "FREQ_TTR"]
